--- #YAML:1.0
name:                Devel-Hide
version:             0.0008
abstract:            Forces the unavailability of specified Perl modules (for testing)
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - A. R. Ferreira <ferreira@cpan.org>
recommends:
    Test::Pod:                     1.18
    Test::Pod::Coverage:           1.04
