---
# http://module-build.sourceforge.net/META-spec.html
name:         Devel-Hide
version:      0.00_02
version_from: lib/Devel/Hide.pm
author:
  - Adriano Ferreira <ferreira@cpan.org>
license: perl
requires:
  Test::More: 0
  #File::Temp: 0 (if $[ < 5.008)
recommends:
  Test::Pod:  1.18
installdirs:  site

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
